name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_OUTPUT

      - name: Run script
        run: |
          chmod +x ./.github/scripts/build-zip
          ./.github/scripts/build-zip status-${{ steps.get_version.outputs.RELEASE_VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: status-${{ steps.get_version.outputs.RELEASE_VERSION }}.zip
